services:
  - type: web
    name: pistach-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pistach-db
          property: connectionString

databases:
  - name: pistach-db
    databaseName: pistach
    user: pistach_user
    plan: free